# Generated by Django 6.0.2 on 2026-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_options_alter_member_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_name',
            field=models.CharField(max_length=100, verbose_name='Тариф/Операция'),
        ),
    ]
