# Generated by Django 6.0.2 on 2026-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_member_amount_paid_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='days_left_before_freeze',
            field=models.IntegerField(default=0, verbose_name='Оставалось дней до заморозки'),
        ),
        migrations.AddField(
            model_name='member',
            name='freeze_until',
            field=models.DateField(blank=True, null=True, verbose_name='Заморожен до'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Заморожен'),
        ),
    ]
