# Generated by Codex on 2026-05-21

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_TRAINERS = [
    {
        "full_name": "Алексей Морозов",
        "specialty": "Минигруппы, силовая подготовка",
        "photo_url": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=480&q=80",
        "notes": "Хорош для новичков и групп до 6 человек.",
    },
    {
        "full_name": "Мария Волкова",
        "specialty": "Индивидуальные тренировки, коррекция техники",
        "photo_url": "https://images.unsplash.com/photo-1609899464726-209befaac5fc?auto=format&fit=crop&w=480&q=80",
        "notes": "Сильная работа с осанкой, техникой и прогрессией нагрузки.",
    },
    {
        "full_name": "Дмитрий Соколов",
        "specialty": "Функциональный тренинг, снижение веса",
        "photo_url": "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=480&q=80",
        "notes": "Активные занятия, контроль питания и регулярные замеры.",
    },
]


def seed_trainers(apps, schema_editor):
    Trainer = apps.get_model("api", "Trainer")
    for item in DEFAULT_TRAINERS:
        Trainer.objects.get_or_create(full_name=item["full_name"], defaults=item)


def remove_seed_trainers(apps, schema_editor):
    Trainer = apps.get_model("api", "Trainer")
    Trainer.objects.filter(full_name__in=[item["full_name"] for item in DEFAULT_TRAINERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_member_days_left_before_freeze_member_freeze_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('specialty', models.CharField(blank=True, default='', max_length=120, verbose_name='Специализация')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.trainer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='payment',
            name='trainer_photo_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Фото тренера'),
        ),
        migrations.RunPython(seed_trainers, remove_seed_trainers),
    ]
